### ISSUE TITLE
TypeError: features.transposeView is not a function

### ISSUE THREAD

**Issue by zemlyansky** [mljs/logistic-regression#6]
`ml-logistic-regression` relies on the old version of `ml-matrix` <6.0.0. So if you recreate example from the README with the latest `ml-matrix` it will throw the `features.transposeView is not a function` error. That can be recreated in [RunKit](https://npm.runkit.com/ml-logistic-regression) and temporary fixed downgrading `ml-matrix`

```javascript
var LogisticRegression = require("ml-logistic-regression")
const {Matrix} = require('ml-matrix');

var X = new Matrix([[0,-1], [1,0], [1,1], [1,-1], [2,0], [2,1], [2,-1], [3,2], [0,4], [1,3], [1,4], [1,5], [2,3], [2,4], [2,5], [3,4], [1, 10], [1, 12], [2, 10], [2,11], [2, 14], [3, 11]]);
var Y = Matrix.columnVector([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]);

var logreg = new LogisticRegression(numSteps = 1000, learningRate = 5e-3);
logreg.train(X,Y)
```

**Comment by targos** [comment]
I upgraded ml-matrix and pushed v2.0.0
